### ISSUE TITLE
MySQL error 1064

### ISSUE THREAD

**Issue by genesisfan** [thotmx/com_efemerides#1]
Hi,
I've installed Efemerides into Joomla 3.3. Added some historic dates and when accessing the front page with Efemerides module configured it shows:

You have an error 1064 in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(NOW())=DAY(historicdate) AND MONTH(NOW())=MONTH(historicdate) AND ORDER BY (h' at line 1 SQL=SELECT id,historicdate as thedate, DAY(historicdate) as theday,MONTH(historicdate) as themonth, YEAR(historicdate) as theyear,title,description FROM j30_efemerides DAY(NOW())=DAY(historicdate) AND MONTH(NOW())=MONTH(historicdate) AND ORDER BY (historicdate), (historicdate), (historicdate)

MySQL version 5.6.17

regards,
Marcel

**Comment by thotmx** [comment]
Did you select an "order_by" option on your configuration panel for this
module?

On Sun, Dec 28, 2014 at 9:18 AM, genesisfan notifications@github.com
wrote:

> Hi,
> I've installed Efemerides into Joomla 3.3. Added some historic dates and
> when accessing the front page with Efemerides module configured it shows:
> 
> You have an error 1064 in your SQL syntax; check the manual that
> corresponds to your MySQL server version for the right syntax to use near
> '(NOW())=DAY(historicdate) AND MONTH(NOW())=MONTH(historicdate) AND ORDER
> BY (h' at line 1 SQL=SELECT id,historicdate as thedate, DAY(historicdate)
> as theday,MONTH(historicdate) as themonth, YEAR(historicdate) as
> theyear,title,description FROM j30_efemerides DAY(NOW())=DAY(historicdate)
> AND MONTH(NOW())=MONTH(historicdate) AND ORDER BY (historicdate),
> (historicdate), (historicdate)
> 
> MySQL version 5.6.17
> 
> regards,
> Marcel
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thotmx/com_efemerides/issues/1.

## 

Hermes Ojeda Ruiz
LogicalBricks Solutions
http://logicalbricks.com

**Comment by genesisfan** [comment]
If you mean order by Month-Day-Year or Day-Month-Year yes I did. None of the options works.

**Comment by thotmx** [comment]
Ok. I'll take a look. Thanks for your report.

**Comment by genesisfan** [comment]
Any news thotmx?

**Comment by thotmx** [comment]
@genesisfan I've problems setting up my environment. Let me a couple of days to take a look to that. I don't know why the configuration parameters don't reach the point where are needed.

**Comment by genesisfan** [comment]
Hi thotmx, how are you? Any news?

**Comment by genesisfan** [comment]
Tell me which access you need thotmx on my environment to troubleshoot?

**Comment by thotmx** [comment]
Hi @genesisfan.
I'm really sorry, I'm not using Joomla anymore, and it has been difficult to find time to setup a development environment and remember all this things. Yesterday, I've configured my development environment using this: https://github.com/joomlatools/joomla-vagrant

This night I'm going to put some hours to figure out what is the problem.

**Comment by thotmx** [comment]
Hi @genesisfan . 

Could you give me more details about the error. 

I've configured an environment using joomla-vagrant (use MySQLi, and a XAMPP on Ubuntu). It's a clean environment, I've installed the component, after that I installed the module, and I changed the configuration without problem.

Could you try removing and reinstalling the module?

The error that you mentioned it's really strange because I can get all the configuration parameters on the module without problems. Are you using some specific Joomla 3.x feature like custom permissions, or something like that?

Sorry because I can't anwser faster.

**Comment by antonions** [comment]
Hello @thotmx 
I am having the same problem. MySQL 5.5.41-37.0, PHP Version    5.4.17, Joomla! 3.3.6.
Site crashes, with that error displayed: 1064 in your SQL syntax ...
Must disable Efemerides Module (1.0 29 May 2014) to get site back.

Com and module worked fine on J2.5 but after upgrade to J3.3.6 and installed com_emeferides_master and mod_efemerides-master this error happened.

**Comment by genesisfan** [comment]
Hi @thotmx, I've uninstall and installed the module again, but I still receive the SQL error. I've no custom permissions or something like that. When I install the old module (v0.5) with the new component it works fine. I don't receive the SQL error. I've got the exact same issue as @antonions describes.

**Comment by thotmx** [comment]
@antonions @genesisfan, could you give me an screenshot?  

(I'm using the Joomla 3.4-Alpha version, and works fine, I'll try with your version).

**Comment by genesisfan** [comment]
@thotmx here is link to my [demo site](http://bit.ly/1yRl2Dp).

**Comment by thotmx** [comment]
@antonions @genesisfan:
Please download the master of the module again and reinstall it.

I think that I found the mistake. It was an stupid error when I refactored some methods. :( unfortunately I don't have automated tests for the module or component, so this kind of things happens.

**Comment by thotmx** [comment]
@antonions @genesisfan:
Please download the master of the module again and reinstall it.

I think that I found the mistake. It was an stupid error when I refactored some methods. :( unfortunately I don't have automated tests for the module or component, so this kind of things happens.

**Comment by antonions** [comment]
@thotmx Unfortunately, still same error.

**Comment by genesisfan** [comment]
Hi @thotmx, also same error after reinstall. I've compared both master modules ZIP downloads with winmerge and they are also the same. So is the master module ZIP okay?

**Comment by thotmx** [comment]
@genesisfan @antonions. Ok, it's fixed now. 

Definitely I need to put some automated tests to the component and the module. The problem was simple but the lacks of automated tests makes difficult to find it.

If you download the module zip again, I'll work.

**Comment by genesisfan** [comment]
Great @thotmx it works!! No SQL error anymore after install the module zip again. Only the day is incorrectly displayed. I've created a January 31 event but it's displayed as January 30. Should I create a new issue for this?

When I use 'Formatted Date = No' the day is displayed correctly. But when I use 'Formatted Date = Yes' and use "j F, Y", "d M, Y" or "d/m/Y" it's displaying 30 instead of 31.

**Comment by thotmx** [comment]
Yes please. But maybe is a timezone error.

**Comment by antonions** [comment]
It works! Nice job! Thanks!
